# Generated by Django 4.0 on 2022-02-05 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game', models.CharField(max_length=20)),
                ('required_time', models.CharField(max_length=100)),
                ('required_rank', models.CharField(max_length=100)),
                ('reward_ingame', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Requirement', to='home.offer'),
        ),
    ]
