# Generated by Django 4.0 on 2022-02-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_offer_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='offers',
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='number_of_recruit_player',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Tag', to='home.Tag'),
        ),
    ]
