# Generated by Django 4.0 on 2022-02-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tag_remove_game_offer_remove_user_offers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
