# Generated by Django 4.0 on 2022-02-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_offer_user_offer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='game',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
