# Generated by Django 4.0 on 2022-02-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_offer_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_name', to='home.game'),
        ),
    ]
