# Generated by Django 4.0 on 2022-03-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0014_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirm_Upassword', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profilepic1.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
