# Generated by Django 4.0 on 2022-03-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_customer_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='confirm_Upassword',
            new_name='confirm_password',
        ),
    ]
